offset changes successful
raahi-chada2004/out_writeapi pull request #19
Opened 2024-07-16 18:26 UTC by raahi-chada2004

2024-07-16 23:07 UTC, agrawal-siddharth requested changes

2024-07-16 23:07 UTC, agrawal-siddharth commented on out_writeapi.go
> +			err := checkResponses(ms_ctx, (*config).appendResults, true, &(*config).mutex)
Add a comment here explaining that we will synchronously wait for the response.

2024-07-16 23:07 UTC, agrawal-siddharth commented on out_writeapi.go
> +	var enableRetries bool
This will be automatically initialized to false, correct? If so, is it necessary to set it to false again below?

2024-07-17 00:40 UTC, raahi-chada2004 commented on out_writeapi.go
> +			err := checkResponses(ms_ctx, (*config).appendResults, true, &(*config).mutex)
Done.

2024-07-17 00:40 UTC, raahi-chada2004 commented on out_writeapi.go
> +	var enableRetries bool
Done.

2024-07-17 16:46 UTC, agrawal-siddharth approved these changes

2024-07-17 16:58 UTC, merged